### ISSUE TITLE
Make Memeland invite-only

### ISSUE THREAD

**Issue by leohhhn** [gnolang/memeland#18]
## Description

In order to add moderation to Memeland and make it available to the public, we need to introduce a form of moderation to it. I suggest we tie Memeland in with `r/users`, so only addresses that are registered in `r/users` can upload memes. Upvoting can be left open to the public.

**Comment by DIGIX666** [comment]
Hey @leohhhn 
https://github.com/gnolang/memeland/pull/24

**Comment by leohhhn** [comment]
Nice! Thanks.
